### PR TITLE
Update celestia-gaia-stardb

### PR DESCRIPTION
**Pull request by SevenSpheres**
@ajtribick's version 1.0.3

see also [CelestiaContent#36](https://github.com/CelestiaProject/CelestiaContent/pull/36)

### CODE REVIEW

**Review by LukeCEL — APPROVED** [review]

**Comment by ajtribick** [comment]
I'd suggest holding off on this. I've found a few cases where different TYC ids are mapped to the same Gaia ID, which results in two stars in the same place. Should have a v1.0.1 with these eliminated fairly soon.

**Review by 375gnu — APPROVED** [review]

**Comment by SevenSpheres** [comment]
bump

**Review by 375gnu — APPROVED** [review]

**Comment by ajtribick** [comment]
In my repository I've bumped the version of `cryptography` specified in `requirements.txt` from 3.0 to 3.2 as the result of a Dependabot alert. No change to the output files.

**Review by LukeCEL — APPROVED** [review]

**Comment by 375gnu** [comment]
please rebase on the current master

**Review by levinli303 — APPROVED** [review]

**Comment by 375gnu** [comment]
@SevenSpheres are you still planning to merge this?

**Pull request merged**
