### PR TITLE
Fix failure if an incorrect URL is pasted

### PR DESCRIPTION
**Pull request by 375gnu**
Closes: #637

+ small code cleanup

the fix part will be backported to 1.6.2

### CODE REVIEW

**Comment by SevenSpheres** [comment]
This fixes Celestia crashing, but when an invalid URL is pasted Celestia should show an error message. Instead nothing happens.

**Comment by eyvallah** [comment]
I think a boolean value/error string could be returned when opening a url. or invoke an error in Alerter?

**Comment by hv-work** [comment]
return type of `Url::goTo` should be changed to `bool` from `void`, the same for `CelestiaCore::goToUrl`, other is easy as well

**Comment by eyvallah** [comment]
still crashes with cel://testurl, stof throws exception

**Comment by 375gnu** [comment]
@eyvallah i'm unable to reproduce your crash, could you build in debug mode and run under debugger to find the fault location?

**Comment by 375gnu** [comment]
okay, now it should catch more errors

not the best solution, but as i said once this should be rewritten from scratch, this is the ugliest part of Celestia. both from design view and implementation

**Comment by eyvallah** [comment]
url.cpp, line 516

**Comment by 375gnu** [comment]
is it with the latest changes?

**Comment by eyvallah** [comment]
> is it with the latest changes?

my bad, forgot to run make install

**Pull request merged**
