### PR TITLE
Update ru.po

### PR DESCRIPTION
**Pull request by Askaniy**

### CODE REVIEW

**Comment by 375gnu** [comment]
we already have complete russian translation at transifex

**Comment by Askaniy** [comment]
Oh, of course, I wanted to see but left an account. I'll compare it with this translation.

**Comment by Askaniy** [comment]
- more correct translation and fixed mistakes (you can compare for yourself)
- use of the same general terms with mobile Celestia
- looks like without including the full translation in this repository mobile Celestia would also not have a full translation

**Comment by 375gnu** [comment]
superseded by #749

**Pull request closed without merging**
