### PR TITLE
[win] Fix initialization of view options checkboxes

### LINKED ISSUE #1332: Spacecraft & minor moon visibility settings "flipped" on native Windows frontend
**Describe the bug**
On Celestia 1.7.0-win, ~~modeled objects are invisible, regardless of object type (moon, spacecraft, etc)~~ spacecraft and minor moons are invisible if their visibility is turned ON in the "View Options" dialog. They are only visible if visibility is turned OFF. ~~Possibly related to #1330.~~ Neither this issue nor #1330 is present on 1.7.0-qt on Windows.

EDIT: WTF, this issue *is* present on cartrite's build as well. I'm sure it wasn't before.

**To Reproduce**
1. Go to any spacecraft or minor moon, e.g. Hubble, with spacecraft/minor moon visibility turned on
2. See error

**Expected behavior**
~~Modeled objects should be visible.~~ Spacecraft and minor moons should be visible when their visibility option is on in the "View Options" dialog, and not when it's off, instead of the other way around.

**Screenshots**
invisihubble

**Desktop (please complete the following information):**
 - OS: Windows
 - Frontend: native Win
 - Version: 1.7.0

### PR DESCRIPTION
**Pull request by ajtribick**
Resolves #1332 - a few of the initializations used XOR instead of AND.

### CODE REVIEW

**Comment by ajtribick** [comment]
@SevenSpheres - can you confirm that this fixes the issue?

**Comment by SevenSpheres** [comment]
Maybe? The automated build failed, so I'd have to mess with Visual Studio again, which I haven't done in some time...

**Comment by SevenSpheres** [comment]
I get an error as early as the vcpkg step (likely an issue with vcpkg or on my end, not with Celestia):
```Error: Building package cspice:x64-windows failed with: BUILD_FAILED```

**Comment by SevenSpheres** [comment]
```
-- Configuring incomplete, errors occurred!
See also "C:/GitHub/Celestia/build64/CMakeFiles/CMakeOutput.log".
MSBUILD : error MSB1009: Project file does not exist.
Switch: ALL_BUILD.vcxproj
```

**Comment by SevenSpheres** [comment]
I got Celestia to compile with @ajtribick's help (the main issue was that the vcpkg packages didn't actually install... I had to reinstall them one at a time). #1332 is fixed, but Celestia has become very slow and a red "X" icon is shown instead of Celestia's normal icon. I'm guessing the latter two are issues on my end though, and not the result of code changes.

**Comment by levinli303** [comment]
> but Celestia has become very slow

I think by default a debug version (no optimization) is built, so it is expected to be slow. you can try to add -DCMAKE_BUILD_TYPE=Release to the CMake command for configuring.

**Pull request merged**
