### PR TITLE
Better gettext

### PR DESCRIPTION
**Pull request by 375gnu**

### CODE REVIEW

**Comment by RacerBG** [comment]
Should I translate "GeomAlbedo", "BondAlbedo" and "Reflectivity" names when this PR is merged or leave them as they are?

Thanks for your effort! :smiley:

**Comment by 375gnu** [comment]
@RacerBG it's better to keep them as is, because they are `celestia.cfg` parameters name.

**Comment by 375gnu** [comment]
@RacerBG i found an error, so please don't update your translation now.

**Comment by 375gnu** [comment]
fixed it

**Comment by RacerBG** [comment]
> 
> 
> fixed it

No problems, I will wait the merge with Master, thanks for fixing it.

**Review by Askaniy — APPROVED** [review]

**Pull request merged**
