### PR TITLE
Fixes and refactorings in globulars rendering

### PR DESCRIPTION
**Pull request by 375gnu**
Globulars were broken since I migrated them to more modern rendering code. Now they produce the same image as 1.6 does.

### CODE REVIEW

**Comment by ajtribick** [comment]
The appearance close-up is much improved. However I think the view from far away is too bright.

cel://Freeflight/2023-02-21T18:45:58.19478Z?x=wCVrj691pgoC&y=7kdWVw4mrPP//////////w&z=TtjieySSper//////////w&ow=0.044617686&ox=0.20519118&oy=-0.97737825&oz=-0.025250802&select=TYC%206271-1396-1&fov=23.50311&ts=1&ltd=0&p=0&rf=136107799&nrf=255&lm=128&tsrc=0&ver=3

v1.7 with this patch (note for some reason the grab image function results in an image with transparency, the "bullethole" effect isn't present in the application itself)
globular_brightness_1_7

v1.6
globular_brightness_1_6

**Comment by 375gnu** [comment]
should be fixed now

**Comment by ajtribick** [comment]
Still seeing rendering with very bright globular clusters.

**Comment by 375gnu** [comment]
@same url? could you provide screenshots?

**Comment by ajtribick** [comment]
Result of the same cel URL with commit 4949b64:

globulars_4949b64

**Comment by 375gnu** [comment]
@ajtribick do you see the proper image now? I have the same image as 1.6 now, only some globulars are twinkling maybe due to z-fighting, i'll try to fix this.

**Comment by ajtribick** [comment]
Seems better though still a lot brighter than the 1.6 version. The behaviour as you move towards/away from the globular clusters also seems a bit odd. E.g. for Terzan 10, the stellar halo suddenly pops out of existence at ~1560 light years. It then gets dimmer as you move to ~2.9 kpc, then brightens again until it suddenly disappears at ~11.3 kpc.

**Comment by 375gnu** [comment]
I don't see any brightness difference (actually it's about 0.1, i haven't figured out why the same code give different result in 1.6 and 1.7):
image

**Comment by ajtribick** [comment]
View from the URL in commit 31e5d39:
globulars_31e5d39

Will try doing some more testing later

**Comment by 375gnu** [comment]
@ajtribick should be fixed now

**Review by ajtribick — APPROVED** [review]

**Pull request merged**
