### PR TITLE
Qtcompile

### PR DESCRIPTION
**Pull request by KseniaPl**
Successful QT5 compilation

### CODE REVIEW

**Comment by theist** [comment]
Hi! 

I added it already as a line comment. I was compiling a clean clone of this repo in a debian 9 and got an error compiling caused by code in this PR.

My build steps where
```
autoreconf -iv
./configure --with-gtk --enable-cairo --enable-theora --with-lua --disable-warnings
make -j -l2
```

And then died here:
```
make[3]: se entra en el directorio '/home/carlos/repos/github.com/CelestiaProject/Celestia/src/cel3ds'
g++ -DHAVE_CONFIG_H -I. -I../.. -I../../src -I../../thirdparty/Eigen    -DNDEBUG -DNO_DEBUG -O2 -g -O2 -ffast-math -fexpensive-optimizations -fomit-frame-pointer -fno-exceptions -fno-check-new -fno-common -MT 3dsmodel.o -MD -MP -MF .deps/3dsmodel.Tpo -c -o 3dsmodel.o 3dsmodel.cpp
g++ -DHAVE_CONFIG_H -I. -I../.. -I../../src -I../../thirdparty/Eigen    -DNDEBUG -DNO_DEBUG -O2 -g -O2 -ffast-math -fexpensive-optimizations -fomit-frame-pointer -fno-exceptions -fno-check-new -fno-common -MT 3dsread.o -MD -MP -MF .deps/3dsread.Tpo -c -o 3dsread.o 3dsread.cpp
3dsread.cpp:18:17: fatal error: QDebug: No existe el fichero o el directorio
 #include<QDebug>
                 ^
compilation terminated.
Makefile:538: fallo en las instrucciones para el objetivo '3dsread.o'
```

Seemed that it is trying to include qt libraries even when I didn't compiled it with qt support

I tried to include the dev packages for Qt5 and Qt4, but it still broke. 

checked out a commit before the merge and the compilation ended well

**Comment by CelestiaProject** [comment]
@theist From now, Celestia works **only with QT**.
Please try to do a compilation with QT and write here any errors appear.

In any case, the adaptation to QT and the full operation at this stage is not yet guaranteed. The work is still going on.

**Comment by theist** [comment]
Using `./configure --with-qt --enable-cairo --enable-theora --with-lua --disable-warnings` got the same error, also configure script informs that it will be using Qt4
```
Front-End: Qt4
Use Lua: yes
Use Theora: yes
```

It looks that there's no explicit option to use Qt5. Is there a configure option for this ?

Seems that C compiler can not find the QDebug.h file maybe the problem is in the makefile. I have the Qt5 development and Qt4 development package installed throught apt. All of this in Debian 9, I'm aware that this is not your main target platform. I can't help more. I'm able to use git and compile things but I do not know C or C++ to try to fix this

As a workarround just now compiling it with gtk support in the commit before the merge (bde82656) is possible in linux.

**Comment by CelestiaProject** [comment]
@theist I do not work with Linux and can not yet say about QT5 / QT4.
When we finish the basic work on adapting the code for QT, you will learn about it from the commits.
We will also write you about it here.

**Pull request merged**
