### PR TITLE
Show Reference Points labels (Closes: #489)

### PR DESCRIPTION
**Pull request by 375gnu**
@SevenSpheres please test https://ci.appveyor.com/project/375gnu/celestia/builds/28618780/artifacts

### CODE REVIEW

**Comment by SevenSpheres** [comment]
I get a message "The application was unable to start correctly (0xc000007b)"

**Comment by 375gnu** [comment]
@SevenSpheres you need visual studio runtime libraries 2015 https://www.microsoft.com/en-us/download/details.aspx?id=48145 32bit

**Comment by SevenSpheres** [comment]
Looks like I already have that installed.

**Comment by 375gnu** [comment]
anyway i was able to test this with wine

**Pull request merged**
