### PR TITLE
[qt] mirror captured imaged

### PR DESCRIPTION
**Pull request by 375gnu**
Closes: #1461

### CODE REVIEW

**Comment by ajtribick** [comment]
This results in the capture being mirrored for me, i.e. applying this change results in the same orientation as for the bug report.

Kubuntu 23.04, Nvidia GTX 1070

**Comment by 375gnu** [comment]
So the problem should be fixed by setting some Qt options.

**Comment by 375gnu** [comment]
Now it should work properly. @ajtribick please check.

**Review by ajtribick — APPROVED** [review]
lgtm

**Pull request merged**
