### PR TITLE
Remove old redundant models

### PR DESCRIPTION
**Pull request by SevenSpheres**

### CODE REVIEW

**Comment by SevenSpheres** [comment]
> are you sure that *.3ds files are not sources for appropriate *.cmod files?

They probably are, but do they really need to be there?

**Comment by Anthony-B-Russo10** [comment]
It’s always to have an archive of this stuff done were.

**Comment by SevenSpheres** [comment]
> It’s always to have an archive of this stuff done were.

I honestly have no idea what you're trying to say here.

**Comment by Anthony-B-Russo10** [comment]
The point is keep the files archived some where.

**Comment by 375gnu** [comment]
If they are sources then we need to keep them in the repository. We just don't need to install them.

**Comment by SevenSpheres** [comment]
I added back the 3DS models. Now removing only the CMS models.

**Comment by SevenSpheres** [comment]
> We just don't need to install them.

If I understand correctly how CMakeLists.txt works, the redundant models _are_ being installed.

**Pull request merged**
