### PR TITLE
Feature/linerender/v3

### PR DESCRIPTION
**Pull request by 375gnu**

### CODE REVIEW

**Comment by levinli303** [comment]
android build: https://dev.azure.com/CelestiaProject/Celestia/_build/results?buildId=1888&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by levinli303** [comment]
noticed a bug, there is a slight change of colors when zooming out.

venus/mercury orbit in this example.
https://user-images.githubusercontent.com/17924287/192096583-32d5954f-8ef7-4670-9405-79eac34c7552.mov

**Comment by 375gnu** [comment]
@levinli303 do you have this issue with stars enabled/disabled in different star modes?

**Comment by levinli303** [comment]
@375gnu the issue exists when star rendering is on.

**Comment by 375gnu** [comment]
Then it's caused by the quad behind the star blending with orbits. The same issue should present with master branch. Could you check and confirm?

**Comment by levinli303** [comment]
master branch did have a slight change in color when zooming out, but was nearly unnoticeable.
https://user-images.githubusercontent.com/17924287/195337288-6efd7d3d-9528-4448-8c19-3f08c9f134f4.mov

**Comment by levinli303** [comment]
> the quad behind the star blending with orbits

from that video, it looks like the orbit in front of the star quad is darkened, not the part behind the quad.

**Comment by 375gnu** [comment]
@levinli303 could you make a capture in renderdoc compatible format?

**Comment by levinli303** [comment]
@375gnu  I've been unable to get renderdoc to work on Mac or Android. it should be easily reproducible, I tested with GL on Mac it has the same issue.

**Pull request closed without merging**
