### PR TITLE
Do not rely on clamp to border on ring textures

### PR DESCRIPTION
**Pull request by levinli303**

### CODE REVIEW

**Comment by 375gnu** [comment]
i'll test it first

**Comment by 375gnu** [comment]
@levinli303 could you provide info where you noticed issues without working clamp_to_border? i want to check if other approaches work?

**Comment by levinli303** [comment]
You can check Uranus/Neptune with ring shadow on.... when clamp_to_border is not available.

**Review by 375gnu — CHANGES_REQUESTED** [review]
@levinli303 please amend your change to be applied only if GL_ES & GL_OES_texture_border_clamp doesn't present?

Because the proposed approach is visually worth (jugged edges) then the original. And older HW doesn't likes branching, so let's don't make worth where we can have a better result.

**Comment by levinli303** [comment]
My Android device has GL_EXT_texture_border_clamp, but not GL_OES_texture_border_clamp, so I made it detect either GL_EXT_texture_border_clamp or GL_OES_texture_border_clamp

**Review by 375gnu — APPROVED** [review]

**Comment by levinli303** [comment]
added a "\n", I tested again and I did noticed that on iOS, sometimes some pixels around the ring shadow edge are flickering, wonder why it is there...

**Comment by levinli303** [comment]
I'll merge first, it is better than a non-functional one.

**Pull request merged**
