### PR TITLE
Turkish Translation reviewed.

### PR DESCRIPTION
**Pull request by Zaryob**
I translated not translated parts and fuzzy tags.

### CODE REVIEW

**Comment by 375gnu** [comment]
Hi @Zaryob, thank you for your contribution. Let me check the errors reported by our CI:
```
/home/vsts/work/1/s/build/po/tr.po:97: 'msgid' and 'msgstr' entries do not both end with '\n'
/home/vsts/work/1/s/build/po/tr.po:102: 'msgid' and 'msgstr' entries do not both end with '\n'
/home/vsts/work/1/s/build/po/tr.po:2114: 'msgid' and 'msgstr' entries do not both end with '\n'
/home/vsts/work/1/s/build/po/tr.po:2118: 'msgid' and 'msgstr' entries do not both end with '\n'
/home/vsts/work/1/s/build/po/tr.po:2899: 'msgid' and 'msgstr' entries do not both end with '\n'
/home/vsts/work/1/s/build/po/tr.po:3181: 'msgid' and 'msgstr' entries do not both end with '\n'
/usr/bin/msgfmt: found 6 fatal errors
```

The reported lines doesn't match to ones in your file, so I need to check them manually.

**Review by Zaryob — COMMENTED** [review]
```
$ mkdir build && cd build
$ cmake ..
CMake Deprecation Warning at CMakeLists.txt:23 (cmake_policy):
  The OLD behavior for policy CMP0071 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Deprecation Warning at CMakeLists.txt:37 (cmake_policy):
  The OLD behavior for policy CMP0004 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- NAIF SPICE is disabled. Not looking for cspice library.
-- Found Eigen3 3.4.0
CMake Warning at CMakeLists.txt:366 (message):
  C++ experimental filesystem library is unusable!

  Will use own implementation.


-- GLUT frontend is disabled.
-- Either not Unix or Gtk frontend is disabled.
-- SDL frontend is disabled.
-- Either not Windows or Windows frontend is disabled.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zaryob/Development/others/Celestia/build
$  make translations
[  0%] Generating ar.gmo
[  4%] Generating be.gmo
[  4%] Generating bg.gmo
[  8%] Generating de.gmo
[  8%] Generating el.gmo
[ 12%] Generating en.gmo
[ 12%] Generating es.gmo
[ 16%] Generating fr.gmo
[ 16%] Generating gl.gmo
[ 16%] Generating hu.gmo
[ 20%] Generating it.gmo
[ 20%] Generating ja.gmo
[ 24%] Generating ko.gmo
[ 24%] Generating lt.gmo
[ 28%] Generating lv.gmo
[ 28%] Generating nl.gmo
[ 32%] Generating no.gmo
[ 32%] Generating pl.gmo
[ 32%] Generating pt.gmo
[ 36%] Generating pt_BR.gmo
[ 36%] Generating ro.gmo
[ 40%] Generating ru.gmo
[ 40%] Generating sk.gmo
[ 44%] Generating sv.gmo
[ 44%] Generating tr.gmo
[ 48%] Generating uk.gmo
[ 48%] Generating zh_CN.gmo
[ 52%] Generating zh_TW.gmo
[ 52%] Built target translations_2
[ 52%] Generating ar.gmo
[ 56%] Generating be.gmo
[ 56%] Generating bg.gmo
[ 60%] Generating de.gmo
[ 60%] Generating el.gmo
[ 64%] Generating es.gmo
[ 64%] Generating fr.gmo
[ 68%] Generating gl.gmo
[ 68%] Generating hu.gmo
[ 68%] Generating it.gmo
[ 72%] Generating ja.gmo
[ 72%] Generating ko.gmo
[ 76%] Generating lt.gmo
[ 76%] Generating lv.gmo
[ 80%] Generating nl.gmo
[ 80%] Generating no.gmo
[ 84%] Generating pl.gmo
[ 84%] Generating pt.gmo
[ 84%] Generating pt_BR.gmo
[ 88%] Generating ro.gmo
[ 88%] Generating ru.gmo
[ 92%] Generating sk.gmo
[ 92%] Generating sv.gmo
[ 96%] Generating tr.gmo
[ 96%] Generating uk.gmo
[100%] Generating zh_CN.gmo
[100%] Generating zh_TW.gmo
[100%] Built target translations_1
[100%] Built target translations
````

**Comment by 375gnu** [comment]
@Zaryob could you merge 2 commits into one?

**Comment by Zaryob** [comment]
> @Zaryob could you merge 2 commits into one?

I made it. Bests....

**Review by 375gnu — APPROVED** [review]

**Comment by 375gnu** [comment]
@Zaryob please change commit message just to "Update Turkish translation". Thanks in advance.

**Review by 375gnu — APPROVED** [review]

**Comment by 375gnu** [comment]
thanks!

**Pull request merged**
