### PR TITLE
update .travis.yml

### PR DESCRIPTION
**Pull request by eyvallah**
make macOS non-failable, and update Xcode

### CODE REVIEW

**Comment by eyvallah** [comment]
urgh, Xcode 11 tries to use the c++ filesystem which is only supported on macOS 10.15, however CI is running in macOS 10.14, that's why the macOS build is throwing errors. I'll see to it later.

**Comment by eyvallah** [comment]
it still defaults to C++ 17 when not linking with c++fs, i think we should introduce a macro to disable use of c++ filesystem in filesystem.h rather than relying totally on cplusplus version @375gnu what do you think?

**Comment by 375gnu** [comment]
Why apple clang uses C++17 despite C++11 set by cmake?

**Comment by eyvallah** [comment]
I'm closing this until travis offers 10.15 machine. the glew package fetched from brew is flawed in cmake config, and will make the linker try to link to OpenGL library in a non-existent path.

**Pull request closed without merging**
