### PR TITLE
Increase Star Render Distance FURTHER

### PR DESCRIPTION
**Pull request by LafuenteAstronomy**
I made a small change to the stardb.cpp file, increasing the star render distance from 1 GLY to 100 GLY. Would you mind checking if this works well with the current programming of Celestia? Thanks

### CODE REVIEW

**Comment by 375gnu** [comment]
This actually require a star database with so distant data, without it the change is useless.

**Comment by GurrenLagannTSS** [comment]
Vision's addons do place real black holes that are beyond the current 1 Gly render limit, so this change might be needed If we want then to work in standard Celestia.

**Comment by SevenSpheres** [comment]
All of Vision's addons released so far work with Janus' version of Celestia 1.7.0, which has exactly the same code change I made (1 Gly limit). I agree with @375gnu here; no one is going to define anything this distant, since it's larger than the observable Universe.

**Comment by LafuenteAstronomy** [comment]
Then, I guess we need to probably merge the code with Janus' code so that GitHub version works as well. And while 100 billion may be beyond the Observable Universe, it may be the best that we can do, since the actual diameter is 93 billion, just 7 billion less.

**Comment by LafuenteAstronomy** [comment]
If only Janus was here to give his insight

**Comment by SevenSpheres** [comment]
> And while 100 billion may be beyond the Observable Universe, it may be the best that we can do, since the actual diameter is 93 billion, just 7 billion less.

The **radius** (which is what matters here) is 46.5 Gly, less than half of 100 Gly.

**Comment by LafuenteAstronomy** [comment]
Perhaps 50 GLY can be made instead. However, for reasons of fictional addons, 100 can be good, it's the call of the developer if it can be tierh 50, 100 or unchanged.. We just need to integrate it with Janus' code, which enables such objects to be present in the first place.

**Comment by SevenSpheres** [comment]
> We just need to integrate it with Janus' code, which enables such objects to be present in the first place.

I guess the Janus build I have increases the star render limit further than 1 Gly.

**Comment by LafuenteAstronomy** [comment]
> > We just need to integrate it with Janus' code, which enables such objects to be present in the first place.
> 
> I guess the Janus build I have increases the star render limit further than 1 Gly.

If I remember, he had a 100 GLY commit. It may be the one you are using

**Comment by 375gnu** [comment]
For me render distance should be configured in celestia.cfg rather than hardcoded.

**Comment by SevenSpheres** [comment]
> For me render distance should be configured in celestia.cfg rather than hardcoded.

[Agreed](https://github.com/CelestiaProject/Celestia/issues/475)

**Pull request closed without merging**
