### PR TITLE
Add openclusters.dsc

### PR DESCRIPTION
**Pull request by SevenSpheres**
This should be credited to @ajtribick if at all possible. I'm waiting on @LukeCEL to make PRs for his stars.dat, cross-index files, and jsdc.stc.

### CODE REVIEW

**Comment by LukeCEL** [comment]
> This should be credited to @ajtribick if at all possible.

Do you know what the license is?

> I'm waiting on @LukeCEL to make PRs for his stars.dat, cross-index files, and jsdc.stc.
Don't hold your breath, I'm afraid. I still need to figure out the details of how PRs work.

**Comment by SevenSpheres** [comment]
> Do you know what the license is?

I'm not sure if it matters for a simple catalog of open clusters, but the file:
- was made by a Celestia developer
- is included in Celestia-ED
- is included in Celestia Origin (with some modifications)

so I think it's fine.

**Comment by ajtribick** [comment]
To be honest I'd completely forgotten I'd made this, I don't think I have a copy of the original any more. The forum attachments seem to have disappeared and the Motherlode is down at the moment, so not sure which license (if any) I originally included. It's possible I only put a license on the Perl script for processing the data that I presumably distributed along with the add-on file.

Instead of using this old file, I'd strongly recommend using a catalogue that incorporates the Gaia results to provide the open cluster locations, especially if you're updating your star database to include Gaia information.

**Comment by SevenSpheres** [comment]
> Instead of using this old file, I'd strongly recommend using a catalogue that incorporates the Gaia results to provide the open cluster locations, especially if you're updating your star database to include Gaia information.

An outdated catalog of open clusters is better than none. Maybe in the future Luke, or myself, or someone else will make an updated catalog, but for now this is all there is.

**Comment by ajtribick** [comment]
Looks like Selden Ball actually has a [Gaia DR2-based add-on on his website](https://www.classe.cornell.edu/~seb/celestia/catalogs.html#3.5.1), which basically does what I would have done, plus a bunch of celx scripts. I would suggest asking if that can be added to the code.

If you really want to go ahead with adding my old file, would a [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license work for you?

**Comment by SevenSpheres** [comment]
> Looks like Selden Ball actually has a Gaia DR2-based add-on on his website, which basically does what I would have done, plus a bunch of celx scripts. I would suggest asking if that can be added to the code.

It looks like the catalog of open clusters in that addon (cocd_all.dsc) is derived from [this](https://heasarc.gsfc.nasa.gov/W3Browse/all/cocd.html), not Gaia data. I'm not sure if it's more up-to-date. The star database in that addon is derived from Gaia _DR1_.

@LukeCEL your thoughts?

**Comment by ajtribick** [comment]
> It looks like the catalog of open clusters in that addon (cocd_all.dsc) is derived from [this](https://heasarc.gsfc.nasa.gov/W3Browse/all/cocd.html), not Gaia data. I'm not sure if it's more up-to-date. The star database in that addon is derived from Gaia _DR1_.

Yes, there's also a Gaia DR1-based add-on there. I was referring to the A93_open_clusters.zip, containing files `named_a93_clusters.dsc` and `unnamed_a93_clusters.dsc`.

**Comment by SevenSpheres** [comment]
> Yes, there's also a Gaia DR1-based add-on there. I was referring to the A93_open_clusters.zip listed immediately below that one.

Well I feel pretty stupid now...I'm closing this PR, I will probably reopen it later with Selden's file.

**Pull request closed without merging**
