### PR TITLE
Generic attributes

### PR DESCRIPTION
**Pull request by 375gnu**
after this commit only GL matrices block our way to the real GL ES

### CODE REVIEW

**Comment by eyvallah** [comment]
Nice! this seems to break globular rendering

**Comment by 375gnu** [comment]
@eyvallah what do you mean? could you provide screenshots, shader log?

**Comment by eyvallah** [comment]
[Screen Recording 2020-05-06 at 11.35.10 PM.zip](https://github.com/CelestiaProject/Celestia/files/4587743/Screen.Recording.2020-05-06.at.11.35.10.PM.zip)
when go to a new object, there is a red triangle

**Comment by eyvallah** [comment]
GL4ES error log

```
LIBGL: Error while compiling shader 22. Original source is:
#version 120

attribute vec3 in_Position;
attribute vec4 in_Color;
attribute float starSize;
attribute float eta;

uniform mat3 m;
uniform vec3 offset;
uniform float brightness;
uniform float pixelWeight;
uniform float RRatio;

const float RRatio_min   = pow(10.0f, 1.7f);
const float clipDistance = 100.0f; // observer distance [ly] from globular, where we
                                   // start "morphing" the star-sprite sizes towards
                                   // their physical values

varying vec4 color;

float relStarDensity(void)
{
    /*! As alpha blending weight (relStarDensity) I take the theoretical
     *  number of globular stars in 2d projection at a distance
     *  rho = r / r_c = eta * r_t from the center (cf. King_1962's Eq.(18)),
     *  divided by the area = PI * rho * rho . This number density of stars
     *  I normalized to 1 at rho=0.

     *  The resulting blending weight increases strongly -> 1 if the
     *  2d number density of stars rises, i.e for rho -> 0.
     */

     float rRatio = max(RRatio_min, RRatio);
     float Xi = 1.0f / sqrt(1.0f + rRatio * rRatio);
     float XI2 = Xi * Xi;
     float rho2 = 1.0001f + eta * eta * rRatio * rRatio; //add 1e-4 as regulator near rho=0

     return ((log(rho2) + 4.0f * (1.0f - sqrt(rho2)) * Xi) / (rho2 - 1.0f) + XI2) / (1.0f - 2.0f * Xi + XI2);
}


void main(void)
{
    vec3 p = m * in_Position.xyz;
    float br = 2 * brightness;

    vec4 mod = gl_ModelViewMatrix * vec4(in_Position, 1.0f);
    float s = 2000.0 / -mod.z * br * starSize;

    float obsDistanceToStarRatio = length(p + offset) / clipDistance;
    // "Morph" the star-sprite sizes at close observer distance such that
    // the overdense globular core is dissolved upon closing in.
    gl_PointSize = s * min(obsDistanceToStarRatio, 1.0f);

    color = vec4(in_Color.rgb, min(1.0f, br * (1.0f - pixelWeight * relStarDensity())));
    gl_Position = gl_ModelViewProjectionMatrix * vec4(p, 1.0f);
}

=======
ShaderConv Source is:
#version 100
precision highp float;
precision highp int;
uniform highp mat4 _gl4es_ModelViewMatrix;
uniform highp mat4 _gl4es_ModelViewProjectionMatrix;
struct _gl4es_PointParameters
{
   float size;
   float sizeMin;
   float sizeMax;
   float fadeThresholdSize;
   float distanceConstantAttenuation;
   float distanceLinearAttenuation;
   float distanceQuadraticAttenuation;
};
uniform _gl4es_PointParameters _gl4es_Point;
float min(float a, int b) {
 return min(a, float(b));
}
float min(int a, float b) {
 return min(float(a), b);
}
float max(float a, int b) {
 return max(a, float(b));
}
float max(int a, float b) {
 return max(float(a), b);
}
float pow(float f, int a) {
 return pow(f, float(a));
}

attribute vec3 in_Position;
attribute vec4 in_Color;
attribute float starSize;
attribute float eta;

uniform mat3 m;
uniform vec3 offset;
uniform float brightness;
uniform float pixelWeight;
uniform float RRatio;

const float RRatio_min   = pow(10.000000, 1.700000);
const float clipDistance = 100.000000; 
                                   
                                   

varying vec4 color;

float relStarDensity(void)
{
    


     float rRatio = max(RRatio_min, RRatio);
     float Xi = 1.000000 / sqrt(1.000000 + rRatio * rRatio);
     float XI2 = Xi * Xi;
     float rho2 = 1.000100 + eta * eta * rRatio * rRatio; 

     return ((log(rho2) + 4.000000 * (1.000000 - sqrt(rho2)) * Xi) / (rho2 - 1.000000) + XI2) / (1.000000 - 2.000000 * Xi + XI2);
}


void main(void)
{
    vec3 p = m * in_Position.xyz;
    float br = 2 * brightness;

    vec4 mod = _gl4es_ModelViewMatrix * vec4(in_Position, 1.000000);
    float s = 2000.000000 / -mod.z * br * starSize;

    float obsDistanceToStarRatio = length(p + offset) / clipDistance;
    
    
    gl_PointSize = s * min(obsDistanceToStarRatio, 1.000000);

    color = vec4(in_Color.rgb, min(1.000000, br * (1.000000 - pixelWeight * relStarDensity())));
    gl_Position = _gl4es_ModelViewProjectionMatrix * vec4(p, 1.000000);
}

=======
Compiler message is
ERROR: 0:68: '*' does not operate on 'int' and 'float'
ERROR: 0:71: Use of undeclared identifier 'br'
ERROR: 0:76: Use of undeclared identifier 's'
ERROR: 0:78: Use of undeclared identifier 'br'

LIBGL: End of Error log
```

**Comment by 375gnu** [comment]
> it seems in globular_vert.glsl there is int * float again...

yeah, i copy them from my manually edited installation

**Comment by 375gnu** [comment]
It looks like selection pointer is broken. why do you think it's globulars?

**Comment by 375gnu** [comment]
regarding the marker issue - do you have it with master branch?

**Comment by eyvallah** [comment]
> regarding the marker issue - do you have it with master branch?

the master branch is OK

**Comment by 375gnu** [comment]
@eyvallah could you test now?

**Comment by eyvallah** [comment]
> @eyvallah could you test now?

the issue persists.

**Comment by 375gnu** [comment]
@LukeCEL @pirogronian @SevenSpheres do you also have the issue from the eyvallah's video?

@eyvallah could you 1) post your /tmp/celestia-shaders.log  2) comment this line https://github.com/CelestiaProject/Celestia/blob/generic-attributes/src/celengine/render.cpp#L1766 and check what happens?

**Comment by 375gnu** [comment]
Have just checked with removed `selpointer_vert.glsl` - and I have the same issue. So either your are missing right  `selpointer_*.glsl` or it reports errors on your system. In the second case I need your `/tmp/celestia-shaders.log`.

**Comment by eyvallah** [comment]
@375gnu with current  generic-attributes branch it works without problem

**Comment by 375gnu** [comment]
let's roll!

**Pull request merged**
