### PR TITLE
C++17-like filesystem API + small fixes

### PR DESCRIPTION
**Pull request by 375gnu**
This library will be used as a fallback if std::experimental::filesystem is not available.

### CODE REVIEW

**Comment by 375gnu** [comment]
@dlshcbmuipmam Could you test this branch? It should work but my mingw crosscompiler is dead :)

**Comment by 375gnu** [comment]
@eyvallah could you also test this branch before merging?

**Comment by eyvallah** [comment]
> @eyvallah could you also test this branch before merging?

it works on my mac, two new warning produces by Xcode:

fs.cpp line 217, 301: Moving a temporary object prevents copy elision

**Comment by 375gnu** [comment]
> fs.cpp line 217, 301: Moving a temporary object prevents copy elision

compilers are more clever than people :)

**Comment by dlshcbmuipmam** [comment]
@375gnu I guess this is related to gcc 9.2 (or 9 in general), Mingw gives me the following error:
```
D:/msys2_64/20190524/home/dlshc/git/Relatoria-project/Celestia/src/celestia/celestiacore.cpp: In member function 'bool CelestiaCore::initSimulation(const std::experimental::filesystem::v1::__cxx11::path&, const std::vector<std::experimental::filesystem::v1::__cxx11::path>&, ProgressNotifier*)':
D:/msys2_64/20190524/home/dlshc/git/Relatoria-project/Celestia/src/celestia/celestiacore.cpp:4101:39: error: no matching function for call to 'std::basic_ifstream<char>::basic_ifstream(const std::experimental::filesystem::v1::__cxx11::path&, const openmode&)'
 4101 |         ifstream dsoFile(file, ios::in);
      |                                       ^
In file included from D:/msys2_64/20190524/home/dlshc/git/Relatoria-project/Celestia/src/celestia/celestiacore.cpp:43:
D:/msys2_64/20190524/mingw64/include/c++/9.2.0/fstream:587:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream(std::basic_ifstream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]'
  587 |       basic_ifstream(basic_ifstream&& __rhs)
      |       ^~~~~~~~~~~~~~
D:/msys2_64/20190524/mingw64/include/c++/9.2.0/fstream:587:7: note:   candidate expects 1 argument, 2 provided
D:/msys2_64/20190524/mingw64/include/c++/9.2.0/fstream:562:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const string&, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::string = std::__cxx11::basic_string<char>; std::ios_base::openmode = std::_Ios_Openmode]'
  562 |       basic_ifstream(const std::string& __s,
      |       ^~~~~~~~~~~~~~
D:/msys2_64/20190524/mingw64/include/c++/9.2.0/fstream:562:41: note:   no known conversion for argument 1 from 'const std::experimental::filesystem::v1::__cxx11::path' to 'const string&' {aka 'const std::__cxx11::basic_string<char>&'}
  562 |       basic_ifstream(const std::string& __s,
      |                      ~~~~~~~~~~~~~~~~~~~^~~
D:/msys2_64/20190524/mingw64/include/c++/9.2.0/fstream:544:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const wchar_t*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]'
  544 |       basic_ifstream(const wchar_t* __s,
      |       ^~~~~~~~~~~~~~
D:/msys2_64/20190524/mingw64/include/c++/9.2.0/fstream:544:37: note:   no known conversion for argument 1 from 'const std::experimental::filesystem::v1::__cxx11::path' to 'const wchar_t*'
  544 |       basic_ifstream(const wchar_t* __s,
      |                      ~~~~~~~~~~~~~~~^~~
D:/msys2_64/20190524/mingw64/include/c++/9.2.0/fstream:529:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]'
  529 |       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
      |       ^~~~~~~~~~~~~~
D:/msys2_64/20190524/mingw64/include/c++/9.2.0/fstream:529:34: note:   no known conversion for argument 1 from 'const std::experimental::filesystem::v1::__cxx11::path' to 'const char*'
  529 |       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
      |                      ~~~~~~~~~~~~^~~
D:/msys2_64/20190524/mingw64/include/c++/9.2.0/fstream:518:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]'
  518 |       basic_ifstream() : __istream_type(), _M_filebuf()
      |       ^~~~~~~~~~~~~~
D:/msys2_64/20190524/mingw64/include/c++/9.2.0/fstream:518:7: note:   candidate expects 0 arguments, 2 provided
```

**Comment by 375gnu** [comment]
@dlshcbmuipmam could pull recent changes?

**Pull request merged**
