### PR TITLE
Fix compilation with older compilers

### PR DESCRIPTION
**Pull request by 375gnu**
E.g. g++ 7.x

### CODE REVIEW

**Comment by ajtribick** [comment]
How far back do we need to support here? E.g. Debian oldstable has 10.2 and oldoldstable is no longer getting standard releases.

**Comment by 375gnu** [comment]
I still use Ubuntu 18.04 with gcc 7. Also what about Android and iOS?

**Comment by 375gnu** [comment]
Oops! You just commented, not approved :)

**Comment by levinli303** [comment]
On Android there is also a fix i added to make NDK happy because NDK never updated their libc++ header since 2020. But that should be fixed in the upcoming NDK release in the future

https://github.com/celestiamobile/Celestia/commit/4e446db036636b0a1254c86eb58bf8e99ee0563a

**Comment by 375gnu** [comment]
@levinli303 could it be added but with appropriate guards, i.e.
```
#if defined(__ANDROID__)
```

later when a fixed NDK is released then we update it to something like
```
#if defined(__ANDROID__) && NDKVERSION < 1234
```

**Comment by levinli303** [comment]
yeah it's possible.  although to make the define __NDK_MAJOR__ work, we need to include another header since the define is not added by compiler.

**Pull request merged**
