### PR TITLE
Remove alpha channel for DXT1 textures

### PR DESCRIPTION
**Pull request by levinli303**
To align with the behaviors of loading DXT1 textures with gl methods. Takin the easy approach here...

### CODE REVIEW

**Comment by 375gnu** [comment]
@levinli303 could you explain purpose of the change? i'm not a specialist in DXT textures

**Comment by levinli303** [comment]
Since in some places when hasAlpha is true on a texture, different render configuration is applied. the gl loaded dxt1 texture' returns false for hasAlpha. while after being transformed to RGBA, the hasAlpha value is true.

**Comment by levinli303** [comment]
Before
Simulator Screen Shot - iPhone 12 - 2021-06-14 at 09 37 39

After
Simulator Screen Shot - iPhone 12 - 2021-06-14 at 09 36 33

**Comment by 375gnu** [comment]
@levinli303 could you then leave a comment with a reference to this PR in the body on your change?

**Comment by levinli303** [comment]
done

**Review by 375gnu — APPROVED** [review]

**Pull request merged**
