### PR TITLE
Fix constellation name in zh_CN.po

### LINKED ISSUE #856: Wrong name of constellations in Chinese version
**Describe the bug**
The name of constellations Vela and Virgo are swapped in Chinese version of Celestia. 
**To Reproduce**
1. Run Celestia in Chinese language
2. Scroll to constellations Vela or Virgo
3. See error
**Screenshots**
微信图片_20201018171617
**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.6.1

### PR DESCRIPTION
**Pull request by levinli303**
closes #856

### CODE REVIEW

**Comment by levinli303** [comment]
I edited directly on Github  and it transformed the line breaks to CRLF it seems.

**Comment by SevenSpheres** [comment]
please backport to 1.6.x as well

**Comment by 375gnu** [comment]
could you convert line endings back?

**Comment by levinli303** [comment]
done, lets merge and then cherry-pick to 1.6.x.

**Review by 375gnu — APPROVED** [review]

**Pull request merged**
