### PR TITLE
Qt ui reorganisation progress

### PR DESCRIPTION
**Pull request by pirogronian**
Some new functions in CelestiaCoreApplication for convenience, qt wrapper on CelestiaCoreApplication and use of this wrapper, where reasonable.

### CODE REVIEW

**Comment by Alexell** [comment]
Is this the final request or wait for the end of your work?

**Comment by pirogronian** [comment]
Final and tested. However, it's a part of longer plan. My finall goal is still complete api replacement of charentered function.

**Comment by Alexell** [comment]
@pirogronian Your changes can not cause a failure of the compilation or work Celestia on Windows? Have you made yourself a Windows virtual operating system for the Celestia test? Or is it all just checking on Linux?

**Comment by pirogronian** [comment]
Linux only. I have no chance to test it on other systems. However I try avoiding any platform specific stuff.

**Pull request merged**
