### PR TITLE
Fix (hopefuly) compile error reported in #269

### PR DESCRIPTION
**Pull request by pirogronian**
Fix (hopefuly) compile error reported in #269

### CODE REVIEW

**Comment by 375gnu** [comment]
I'd prefer a bug report to fmt repo done instead of fixing their issues.

**Comment by pirogronian** [comment]
If fmt authors introduced their own version of char_traits it doesn't seem to necessarily be a bug. However, can be reported for being sure.

**Comment by 375gnu** [comment]
If internal API interfere with public one then for it's a bug. Even if it won't be fixed there is no need to change a whole file, just adding `std::` to `char_traits` is enough.

**Comment by 375gnu** [comment]
fmt was fixed so i closing the PR

**Pull request closed without merging**
