### PR TITLE
[help] Update Celestia Guide

### PR DESCRIPTION
**Pull request by dave-kaye**
Update the Celestia Guide with new Install and Command Line sections, make the FAQ Vista section more Windows generic, plus other minor information updates.

### CODE REVIEW

**Comment by dave-kaye** [comment]
This is an update to the Celestia Guide. It appears that the file was originally built in 2009 and has not had major updating since then. The Linux and Unix install section consisted of compiling instructions for GTK, KDE and Gnome interfaces. It was completely rebuilt to a general install section for multiple operating systems.  A new documentation section for Celestia command line options was added.  Most of the Windows Vista FAQ section was generalized to Windows.  Vista is used on only an estimated 0.12% of computers, and has been at end of support by Microsoft since 2017. The accuracy of answers was not verified for this section, but they are general in nature. Other minor cosmetic changes were also done. The complete document was not checked for accuracy, but appears to be OK. When a link was found, it was tested to see if it was still valid. The document was left generic, allowing for both Celestia 1.7.0 and 1.6.3 use. Future work could target the document to 1.7.0 when necessary.

This effort required changes in the *.css file. I do know of nor have the original software that created the file. I used a text editor to add several minor css elements. I do not have a css file check program. I tested the guide on Windows Chrome, Firefox and Edge browsers; as well as Linux Firefox and Chromium browsers. It worked on all of the browsers.

**Installation**

- Celestia 1.6.3 - The Linux installation (GTK and GLUT) was tested on openSUSE Tumbleweed. The Windows (native) installation was tested on openSUSE Leap 15.2 using a VirtualBox 6.1.10 virtual machine running Windows 10 22H2. The AppImage was tested on openSUSE Leap 15.2. The macOS was not tested as I have no equipment.

- Celestia 1.7.0 - The Linux installation (GTK, Qt5 and SDL) was tested on openSUSE Leap 15.2. The AppImage was tested on openSUSE Tumbleweed. I searched but found no macOS installation pre-built packages.  

- There are no current instructions for the installation of Celestia 1.7.0 in Windows. All information I found was outdated and inaccurate.  Using openSUSE Leap 15.2, I created a VirtualBox 6.1.10 virtual machine running Windows 10 22H2 - which required mesa3d project openGL drivers to achieve an openGL version 2.1. I recorded all the steps needed to install the software using the GitHub artifacts saved during updates. The Win native, Qt5 and Qt6 interfaces were all installed. All appeared to run successfully with simple activities. The only noticeable error was the lack of the splash startup screen on all interfaces. It was not seen at all in Windows, and was a small white square in Qt. I am not familiar with multi-language support, and left that section of the installation to the user.

The installation of Windows 10 was a fresh installation for each version to prevent cross-contamination.  As Windows does not supply Visual C++ runtime dlls, the Visual C++ redistributable pack needed to be installed.

**Command Line**

The command line options were obtained from WikiBooks, the help option and reviewing the source code. Each interface was then tested as outlined below.  Each option was working except as noted. Working or encoded but buggy options were added to the guide.

- KDE - KDE3 was tested using openSUSE Leap 15.2 using a VirtualBox 6.1.10 virtual machine running openSUSE 10.3 and Celestia 1.5.0. The url cel:// switch appeared to load but did not run. The url script file ran successfully.

- GTK - GTK3 was tested using openSUSE Leap 15.2 and Celestia 1.6.2/1.7.0. The url option failed to operate, and followed the bug report #1103.

- Qt - Qt5 was tested using openSUSE Leap 15.2 and Celestia 1.7.0. The url option failed to operate, and followed the bug report #1103.

- Win native - The Win code was tested on openSUSE Leap 15.2 using a VirtualBox 6.1.10 virtual machine running Windows 10 22H2 and Celestia 1.6.3. The output from the verbose option could not be found, and followed bug report #1625.

- macOS - Native macOS was not tested as I do not have access to a Mac machine.  No documentation or code could be found to indicate that switches are present.

There are two items that I found along the way:

1) I think @SevenSpheres should also review this information as they seem to have an interest in Celestia documentation.

2) I do not know the effort or requirements, so I naively ask this question.  In the testing of version 1.7.0, I see that the Qt code is being compiled for macOS. Is it possible to save the artifacts similar to Windows? Then could a macOS user duplicate the install procedure listed in the Windows section and record the necessary steps? This would give Mac users a way to run 1.7.0.

This work is submitted for your consideration. If you wish to use it, please make minor changes to the work as you see fit. I have enabled modifications by maintainers. If major revisions are needed, I will delete and resubmit. I must use the web interface to GitHub which is much more limited than Git, so I cannot make modifications to the submission without deleting the present submission and any comments attached to it.

**Comment by dave-kaye** [comment]
Codacy Static Code Analysis wants the 4 lines of margin settings in the css file to be shortened to a single line.  The entire css file is written with the 4 lines settings of multiple items.  The issue is minor severity and will not block the upload. I am not making the change since I would prefer to match the existing document and don't think the effort of re-writing the entire css file to single line format is worth it.

**Comment by SevenSpheres** [comment]
> I do not know the effort or requirements, so I naively ask this question. In the testing of version 1.7.0, I see that the Qt code is being compiled for macOS. Is it possible to save the artifacts similar to Windows? Then could a macOS user duplicate the install procedure listed in the Windows section and record the necessary steps? This would give Mac users a way to run 1.7.0.

Celestia 1.7.0 for macOS is available as part of the mobile Celestia project, through the [App Store](https://apps.apple.com/us/app/celestia-space-simulator/id1500434829) and [GitHub](https://apps.apple.com/us/app/celestia-space-simulator/id1500434829). This needs to be corrected in the guide.

Some other minor copyediting could be done, like changing "GitHub website" to "GitHub repository", and changing
`Celestia fails to start with messages of files <i>MSVCP140.DLL</i> and <i>VCRUNTIME140.DLL</i> are missing.`
to
`Celestia may fail to start with messages that files <i>MSVCP140.DLL</i> and <i>VCRUNTIME140.DLL</i> are missing.`

**Comment by dave-kaye** [comment]
Is this version 1.7.0?  I know of the mobile website, but the release numbers are different and it appears to have modifications for mobile devices to create an app.  I am not familiar with Mac or iPhone, and do not know the desktop vs mobile program changes that are needed.  Also, is this site constantly updated to the developing software?  unix9 is running scripts on openSUSE build services to package the newest codes automatically for Linux and AppImage.  If developers agree the mobile site is the same 1.7.0 as the main CelestiaProject site, a modification can be made to the macOS entry.  If it is close, then a note of this can be added to the macOS entry that it available in slightly modified or delayed form.

The request/suggestion for macOS artifacts can still be valid if there are modifications and a user wants the same desktop version that others have.

Thank you @SevenSpheres for this information and taking the time to look at the submission.

**Comment by SevenSpheres** [comment]
> Is this version 1.7.0?

Yes, only the frontend is different.

**Comment by levinli303** [comment]
> If it is close, then a note of this can be added to the macOS entry that it available in slightly modified or delayed form.

It uses the same code so it is unmodified, but since new build is not generated every commit, it is slightly delayed.

> Command Line

no command line option is accepted for either 1.6.x or the 1.7.0 (1.5.x on .mobi) on macOS

> I see that the Qt code is being compiled for macOS. Is it possible to save the artifacts similar to Windows? Then could a macOS user duplicate the install procedure listed in the Windows section and record the necessary steps?

Qt build is not in an app bundle format that most macOS users use, it is better distributed via HomeBrew but it only makes sense for final releases not per commit build https://github.com/CelestiaProject/Celestia/issues/1583

**Comment by dave-kaye** [comment]
Updating submission based upon reviewers input. 

Thank you to all.

**Pull request closed without merging**
