### PR TITLE
1.6.x windows setup

### PR DESCRIPTION
**Pull request by ajtribick**
Checking whether we can automate building the Windows installer

Based on top of #1662 but targeting 1.6.x for workflow triggering

### CODE REVIEW

**Comment by levinli303** [comment]
i do not think eigen is used in 1.6.x, is it?

**Comment by 375gnu** [comment]
> i do not think eigen is used in 1.6.x, is it?

Yes, migration started in 1.7

**Comment by ajtribick** [comment]
Blocked on https://github.com/microsoft/vcpkg/pull/30546

**Review by 375gnu — APPROVED** [review]

**Comment by ajtribick** [comment]
@375gnu - how would you prefer to handle merging this, since currently it contains the commit in #1662 - do you want to cherry-pick this into that PR, or merge this one?

**Comment by 375gnu** [comment]
Let's merge this

**Pull request merged**
