### PR TITLE
Git submodules

### PR DESCRIPTION
**Pull request by 375gnu**
Currently to play with only.

### CODE REVIEW

**Comment by 375gnu** [comment]
Glew should be reverted

**Comment by pirogronian** [comment]
What's wrong with glew?

**Comment by 375gnu** [comment]
Ping @pirogronian . Are you ready to use git submodules?

**Comment by pirogronian** [comment]
Shame to admit, I didn't pay a lot of attention to it (in particular I've never tested it on real example). But in theory it looks quiet clear. It shouldn't be much more difficult than switching to cmake.

**Pull request merged**
