### PR TITLE
Add openclusters.dsc (3rd try)

### PR DESCRIPTION
**Pull request by SevenSpheres**
Credit to @ajtribick. Was #551, then #562.

Pinging @LukeCEL again for the other data updates...

### CODE REVIEW

**Comment by 375gnu** [comment]
Have you got an idea when this file was created? I need this info for debian/copyright

**Comment by SevenSpheres** [comment]
The "last modified" date is 2008, so then or before. Old, I know.

**Comment by LukeCEL** [comment]
> Pinging @LukeCEL again for the other data updates...

But my data updates don't just include newer Gaia DR2 data, they also add additional TYC stars.

**Comment by munix9** [comment]
openclusters.dsc is missing in data/CMakeLists.txt?

**Comment by eyvallah** [comment]
> openclusters.dsc is missing in data/CMakeLists.txt?

ok ill take care of that

**Comment by 375gnu** [comment]
shame on me

**Pull request merged**
