### PR TITLE
Backport win32 fixes

### PR DESCRIPTION
**Pull request by levinli303**
Backport changes in #779

Not tested.

### CODE REVIEW

**Comment by 375gnu** [comment]
currently i don't have access to my VM with win, but i'll test it as soon as i have it

**Comment by 375gnu** [comment]
I applied some fixes, now it can be compiled, in my locale it looks good. I put test binaries to https://celestia.space/forum/viewtopic.php?p=150053#p150053

**Comment by SevenSpheres** [comment]
Should this PR be merged, or closed since there's already a [final 1.6.2 release](https://celestia.space/forum/viewtopic.php?p=151566#p151566)?

**Comment by levinli303** [comment]
The issues on 1.6.2 was not fixed somehow by this back port

**Pull request closed without merging**
