### PR TITLE
Update star textures

### LINKED ISSUE #113: Fix colours of star spectral classes
Reported by users

### PR DESCRIPTION
**Pull request by SevenSpheres**
Now they match the Blackbody D65 star colors. Most textures are by FarGetaNik in Project Echoes. The Y dwarf texture is by Edasich, the white dwarf texture is by Frank Gregorio, and the neutron star texture is by Cham. Closes #113.

### CODE REVIEW

**Comment by 375gnu** [comment]
What about their licenses? For 1.7 we accept only free licenses.

**Comment by SevenSpheres** [comment]
I'm sure FarGetaNik is fine with his textures being used, but I don't know about the licenses for the source images. For the others:
Y dwarf: "This add-on may be freely used by Celestia users."
White dwarf: whatever the license for Celestia-ED is
Neutron star: "This addon is free and may be edited as you wish, but only if it's related to Celestia and education."

**Comment by 375gnu** [comment]
SDO & White dwarf are ok. Y dwarf and Neutron star are nonfree

**Comment by SevenSpheres** [comment]
I will remove the neutron star texture. I asked FarGetaNik about the others (M, T, and Y)

**Comment by SevenSpheres** [comment]
Am I overusing rebase? :-)

**Comment by pirogronian** [comment]
@SevenSpheres No :-)

**Comment by 375gnu** [comment]
Let's wait for @Askaniy, cause Celestia Origin team has textures for at least some star classes.

**Comment by SevenSpheres** [comment]
> Celestia Origin team has textures for at least some star classes.

But they aren't the right colors. License for the other textures:

M star: "The images and movies found here are free for publication provided that proper credits are given."
T star: "The T star texture I'm using wasnt published with any license, it's simply a randomly generated texture by JVV he posted on the Celestial matters forum iirc." i.e. we don't know

So the T and Y textures may need to be replaced.

**Comment by SevenSpheres** [comment]
Trying to make a new Y dwarf texture from Jupiter...not working too well...
jupiter-ytest

**Comment by SevenSpheres** [comment]
I just removed the T and Y textures also. Now all textures are free use.

**Comment by SevenSpheres** [comment]
Found [this](https://celestia.space/forum/viewtopic.php?p=144529#p144529):

> all of mine are
> CC-BY-SA
> 
> so there are two credit lines
> 
> 1) NASA/JPL /John Van Vliet
> 2) ESA / John Van Vlet

I'll add the T dwarf texture back.

**Comment by SevenSpheres** [comment]
I just realized that Celestia also uses the neutron star texture for black holes, so it's _definitely_ best to keep them texture-less.

**Comment by SevenSpheres** [comment]
Closing this pull request because Celestia data is in its own repository now.

**Pull request closed without merging**
