### PR TITLE
Move splash.png to splash directory

### PR DESCRIPTION
**Pull request by SevenSpheres**
> [splash.png is beeing searched in another location - in the splash/ subfolder. This was changed to be consistent with other interfaces.](https://celestia.space/forum/viewtopic.php?p=148492#p148492)

Then it needs to actually be there.

### CODE REVIEW

**Comment by SevenSpheres** [comment]
#666 😈

**Comment by 375gnu** [comment]
no need, this is handled by cmake
https://github.com/CelestiaProject/Celestia/blob/master/CMakeLists.txt#L335

**Comment by SevenSpheres** [comment]
Some of us (e.g. me) are using the files from GitHub + the binaries from Appveyor. The files should be in the right place *in the repository.*

**Comment by SevenSpheres** [comment]
> in this case this pr should change all relevant files

*sigh...*

Like what?

**Comment by 375gnu** [comment]
cmake files

**Pull request closed without merging**
