### PR TITLE
Fix garbled text displaying unicode

### LINKED ISSUE #875: [1.6.2] Solar System Browser planet names are in gibberish
**Describe the bug**
The names of the planets in the Bulgarian language (I guess the bug will be the same in Russian too) are in gibberish instead of Bulgarian.

**To Reproduce**
1. Use the Bulgarian language (as I wrote _I think_ Russian will be affected too).
2. Open the Solar System Browser.

**Expected behavior**
The names of the planets should be in their native language.

**Screenshots**
bug

**Desktop (please complete the following information):**
 - Windows 7 SP1 x64
 - Frontend: Native
 - Version: 1.6.2 Final

I haven't noticed other other instances of this bug. I believe that this is a Unicode problem.

### PR DESCRIPTION
**Pull request by levinli303**
Closes #875

### CODE REVIEW

**Comment by levinli303** [comment]
should fix some of them in star browser, solar system browser, eclipse finder, bookmark organizer

**Comment by levinli303** [comment]
always use the W version to set up list view and tree view. also fixed the issue delete a folder in bookmark organizer crashes Celestia. @RacerBG  I can provide an .exe to test, but I do not know if it will be compatible with Win7, my build setup is with VS2019

**Comment by RacerBG** [comment]
> n provide an .

We can try.

> Windows 7 SP1 (with latest Windows Updates): Home Premium, Professional, Enterprise, Ultimate

This from Visual Studio 2019 System Requirements.

https://docs.microsoft.com/en-us/visualstudio/releases/2019/system-requirements

**Comment by levinli303** [comment]
@375gnu can you generate a binary for this PR? my setup is different, so I'm certain providing an .exe won't be sufficient from my side.

**Comment by 375gnu** [comment]
i can but in a few days

**Comment by 375gnu** [comment]
@RacerBG @Askaniy please test https://celestia.space/files/celestia/celestia-1.6.2.1.7z

**Comment by RacerBG** [comment]
@375gnu  @levinli303 

Good job guys, it works!

works

**Review by 375gnu — APPROVED** [review]

**Pull request merged**
