### PR TITLE
deb: remove celestia-data package

### PR DESCRIPTION
**Pull request by 375gnu**
will not merge it immediately, only when @munix9 has setup OBS infrastructure for a new package

### CODE REVIEW

**Comment by munix9** [comment]
what about
```
rm cmake/install_to_extras_subdir.cmake
```
```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -61,7 +61,6 @@ endif()
 include(CheckIncludeFiles)
 include(CheckIncludeFileCXX)
 include(FastMath)
-include(install_to_extras_subdir)
 if(NOT WIN32)
   include(cotire)
 else()
@@ -341,16 +340,11 @@ endif()
 add_subdirectory(src)
 add_subdirectory(po)
 add_subdirectory(po2)
-add_subdirectory(data)
-add_subdirectory(extras)
-add_subdirectory(extras-standard)
 add_subdirectory(fonts)
 add_subdirectory(images)
 add_subdirectory(locale)
-add_subdirectory(models)
 add_subdirectory(scripts)
 add_subdirectory(shaders)
-add_subdirectory(textures)
 
 if(ENABLE_TESTS)
   enable_testing()
```
otherwise the data will be installed and errors will be generated during package creation.

**Comment by munix9** [comment]
The new package "celestia-data" from CelestiaProject/CelestiaContent was created on OBS.
The release is currently disabled (waiting for the merge).

https://build.opensuse.org/package/show/home:munix9:unstable/celestia-data
https://build.opensuse.org/project/monitor/home:munix9:unstable

**Comment by 375gnu** [comment]
@eyvallah please check if macos build can be built properly with this change

**Comment by eyvallah** [comment]
there are some warnings using Clang, it's unrelated to the PR, but I'm too lazy to open an issue for that.


```
In file included from /Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/dsodb.cpp:22:
In file included from /Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/dsodb.h:20:
In file included from /Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/dsooctree.h:17:
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:208:9: warning: instantiation of variable 'DynamicOctree<DeepSkyObject *,
      double>::limitingFactorPredicate' required here, but no definition is available [-Wundefined-var-template]
    if (limitingFactorPredicate(obj, exclusionFactor) || straddlingPredicate(cellCenterPos, obj, exclusionFactor) )
        ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/dsodb.cpp:389:15: note: in instantiation of member function
      'DynamicOctree<DeepSkyObject *, double>::insertObject' requested here
        root->insertObject(DSOs[i], DSO_OCTREE_ROOT_SIZE);
              ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:79:41: note: forward declaration of template entity is here
   static LimitingFactorPredicate*      limitingFactorPredicate;
                                        ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:208:9: note: add an explicit instantiation declaration to suppress this warning if
      'DynamicOctree<DeepSkyObject *, double>::limitingFactorPredicate' is explicitly instantiated in another translation unit
    if (limitingFactorPredicate(obj, exclusionFactor) || straddlingPredicate(cellCenterPos, obj, exclusionFactor) )
        ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:208:58: warning: instantiation of variable 'DynamicOctree<DeepSkyObject *,
      double>::straddlingPredicate' required here, but no definition is available [-Wundefined-var-template]
    if (limitingFactorPredicate(obj, exclusionFactor) || straddlingPredicate(cellCenterPos, obj, exclusionFactor) )
                                                         ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:80:41: note: forward declaration of template entity is here
   static StraddlingPredicate*          straddlingPredicate;
                                        ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:208:58: note: add an explicit instantiation declaration to suppress this warning if
      'DynamicOctree<DeepSkyObject *, double>::straddlingPredicate' is explicitly instantiated in another translation unit
    if (limitingFactorPredicate(obj, exclusionFactor) || straddlingPredicate(cellCenterPos, obj, exclusionFactor) )
                                                         ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:222:86: warning: instantiation of variable 'DynamicOctree<DeepSkyObject *, double>::SPLIT_THRESHOLD'
      required here, but no definition is available [-Wundefined-var-template]
            if (_objects != nullptr && _objects->size() >= DynamicOctree<OBJ, PREC>::SPLIT_THRESHOLD)
                                                                                     ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:77:24: note: forward declaration of template entity is here
   static unsigned int SPLIT_THRESHOLD;
                       ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:222:86: note: add an explicit instantiation declaration to suppress this warning if
      'DynamicOctree<DeepSkyObject *, double>::SPLIT_THRESHOLD' is explicitly instantiated in another translation unit
            if (_objects != nullptr && _objects->size() >= DynamicOctree<OBJ, PREC>::SPLIT_THRESHOLD)
                                                                                     ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:264:42: warning: instantiation of variable 'DynamicOctree<DeepSkyObject *, double>::decayFunction'
      required here, but no definition is available [-Wundefined-var-template]
                                         decayFunction(exclusionFactor));
                                         ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:223:17: note: in instantiation of member function 'DynamicOctree<DeepSkyObject *, double>::split'
      requested here
                split(scale * 0.5f);
                ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/dsodb.cpp:389:15: note: in instantiation of member function
      'DynamicOctree<DeepSkyObject *, double>::insertObject' requested here
        root->insertObject(DSOs[i], DSO_OCTREE_ROOT_SIZE);
              ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:81:41: note: forward declaration of template entity is here
   static ExclusionFactorDecayFunction* decayFunction;
                                        ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:264:42: note: add an explicit instantiation declaration to suppress this warning if
      'DynamicOctree<DeepSkyObject *, double>::decayFunction' is explicitly instantiated in another translation unit
                                         decayFunction(exclusionFactor));





In file included from /Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/stardb.cpp:21:
In file included from /Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/stardb.h:21:
In file included from /Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/staroctree.h:17:
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:208:9: warning: instantiation of variable 'DynamicOctree<Star, float>::limitingFactorPredicate'
      required here, but no definition is available [-Wundefined-var-template]
    if (limitingFactorPredicate(obj, exclusionFactor) || straddlingPredicate(cellCenterPos, obj, exclusionFactor) )
        ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/stardb.cpp:1388:15: note: in instantiation of member function 'DynamicOctree<Star, float>::insertObject'
      requested here
        root->insertObject(unsortedStars[i], STAR_OCTREE_ROOT_SIZE);
              ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:79:41: note: forward declaration of template entity is here
   static LimitingFactorPredicate*      limitingFactorPredicate;
                                        ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:208:9: note: add an explicit instantiation declaration to suppress this warning if
      'DynamicOctree<Star, float>::limitingFactorPredicate' is explicitly instantiated in another translation unit
    if (limitingFactorPredicate(obj, exclusionFactor) || straddlingPredicate(cellCenterPos, obj, exclusionFactor) )
        ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:208:58: warning: instantiation of variable 'DynamicOctree<Star, float>::straddlingPredicate' required
      here, but no definition is available [-Wundefined-var-template]
    if (limitingFactorPredicate(obj, exclusionFactor) || straddlingPredicate(cellCenterPos, obj, exclusionFactor) )
                                                         ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:80:41: note: forward declaration of template entity is here
   static StraddlingPredicate*          straddlingPredicate;
                                        ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:208:58: note: add an explicit instantiation declaration to suppress this warning if
      'DynamicOctree<Star, float>::straddlingPredicate' is explicitly instantiated in another translation unit
    if (limitingFactorPredicate(obj, exclusionFactor) || straddlingPredicate(cellCenterPos, obj, exclusionFactor) )
                                                         ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:222:86: warning: instantiation of variable 'DynamicOctree<Star, float>::SPLIT_THRESHOLD' required
      here, but no definition is available [-Wundefined-var-template]
            if (_objects != nullptr && _objects->size() >= DynamicOctree<OBJ, PREC>::SPLIT_THRESHOLD)
                                                                                     ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:77:24: note: forward declaration of template entity is here
   static unsigned int SPLIT_THRESHOLD;
                       ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:222:86: note: add an explicit instantiation declaration to suppress this warning if
      'DynamicOctree<Star, float>::SPLIT_THRESHOLD' is explicitly instantiated in another translation unit
            if (_objects != nullptr && _objects->size() >= DynamicOctree<OBJ, PREC>::SPLIT_THRESHOLD)
                                                                                     ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:264:42: warning: instantiation of variable 'DynamicOctree<Star, float>::decayFunction' required here,
      but no definition is available [-Wundefined-var-template]
                                         decayFunction(exclusionFactor));
                                         ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:223:17: note: in instantiation of member function 'DynamicOctree<Star, float>::split' requested here
                split(scale * 0.5f);
                ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/stardb.cpp:1388:15: note: in instantiation of member function 'DynamicOctree<Star, float>::insertObject'
      requested here
        root->insertObject(unsortedStars[i], STAR_OCTREE_ROOT_SIZE);
              ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:81:41: note: forward declaration of template entity is here
   static ExclusionFactorDecayFunction* decayFunction;
                                        ^
/Users/lilinfeng/Developer/Xcode/Celestia161/src/celengine/octree.h:264:42: note: add an explicit instantiation declaration to suppress this warning if
      'DynamicOctree<Star, float>::decayFunction' is explicitly instantiated in another translation unit
                                         decayFunction(exclusionFactor));
                                         ^
```

**Comment by 375gnu** [comment]
once i tried to fix first error but unsuccessfully.

**Comment by munix9** [comment]
@375gnu The new packages were released on OBS.
Please check the result.

**Comment by 375gnu** [comment]
@munix9 I checked and they look fine! Thank you!

**Pull request merged**
