### PR TITLE
Use shaders to draw object as point

### PR DESCRIPTION
**Pull request by 375gnu**

### CODE REVIEW

**Comment by eyvallah** [comment]
this seems to have affected halo rendering

screenshot

**Comment by 375gnu** [comment]
@eyvallah what do you mean? i don't see any difference.

so far i have another issue.

**Comment by eyvallah** [comment]
screenshot

@375gnu  it used to be brighter

**Comment by 375gnu** [comment]
this version is basically the same what we had disabled but with newer api. i don't like it, but this code performance impact is not so important, so we can optimize it later

**Comment by 375gnu** [comment]
@eyvallah regarding halo change, the same in this PR. I believe the problem is in star rendering, seems it has some implicit dependencies on other code parts, this present in 1.6.1 as well. Press Ctrl+S to change starfield rendering style and you'll see that Sun changes it's halo. I suppose it's better to create a separate issue for this problem.

**Comment by 375gnu** [comment]
ping @pirogronian

**Pull request merged**
