### PR TITLE
Fix BlendTexture property (Fixes: #602)

### PR DESCRIPTION
**Pull request by 375gnu**

### CODE REVIEW

**Comment by SevenSpheres** [comment]
Confirming that this fixes the bug.

**Comment by SevenSpheres** [comment]
This does indeed fix both #602 and #662, but it seems to make `BlendTexture` work incorrectly for Solar System bodies:
Sedna before this commit:
sedna-nobug
Sedna after this commit:
sednabug

**Comment by 375gnu** [comment]
I have reverted the change which influenced Sedna, though i might apply other changes.

**Comment by 375gnu** [comment]
but i have found another issues, so make this WIP for a while

**Comment by 375gnu** [comment]
now everything should be fine

**Pull request merged**
