### PR TITLE
Reorder

### PR DESCRIPTION
**Pull request by dlshcbmuipmam**
Related to #352 .

I have moved cmdparser.*, command.*, and execution.* from celengine to celestia. Modify cmake files so that the dependencies are clear, and make them more readable. celephem is now compiled to object instead of library.

I have encounter a strange stuff, you can see, a few file changes are stated by git even if I didn't do anything on them. I have to open Celestia.ico with gimp and export it again to compile the program.

The third commit modified how celephem is treated when compiling. It is now technically merged with the celengine library, the directory exist for storing the phenomena-related code (?). I can revert this commit if you don't like it, or go further to merge celengine and celephem completely.

It now has a clearer dependency:
celestia: celengine (+celephem), celmath, celtxf, celutil
celengine (+celephem): cel3ds, celmath, celmodel, celtxf, celutil
cel3ds: celutil
celmodel: celutil
celtxf: celutil
celutil: celmath
celmath:

[dependencies.pdf](https://github.com/CelestiaProject/Celestia/files/3491318/dependencies.pdf)

### CODE REVIEW

**Comment by dlshcbmuipmam** [comment]
I have tested it on my Mingw compiler and MSVC compiler. I will do it on my Linux Mint (with Spice, it never works in my Window) as well, probably today.

**Comment by dlshcbmuipmam** [comment]
In case you want to replicate the Celestia.ico bug, this is what I have done in my first commit in a scripted way.

`
cd src
mv celengine/cmdparser.* celestia/; mv celengine/command.* celestia/; mv celengine/execution.* celestia/
find . -name "cmdparser.h" -type f -exec sed -i 's/<celengine\/command.h>/\"command.h\"/g w /dev/stdout' {} \;
find . -name "cmdparser.cpp" -type f -exec sed -i '/\"astro.h\"/d' {} \;
find . -name "cmdparser.cpp" -type f -exec sed -i 's/<celestia\/celx.h>/\"celx.h\"/g w /dev/stdout' {} \;
find . -name "cmdparser.cpp" -type f -exec sed -i 's/<celestia\/celx_internal.h>/\"celx_internal.h\"/g w /dev/stdout' {} \;
find . -name "cmdparser.cpp" -type f -exec sed -i 's/\"glcontext.h\"/<celengine\/glcontext.h>/g w /dev/stdout' {} \;
find . -name "command.cpp" -type f -exec sed -i 's/\"astro.h\"/<celengine\/astro.h>/g w /dev/stdout' {} \;
find . -name "command.cpp" -type f -exec sed -i 's/\"asterism.h\"/<celengine\/asterism.h>/g w /dev/stdout' {} \;
find . -name "command.cpp" -type f -exec sed -i 's/\"glcontext.h\"/<celengine\/glcontext.h>/g w /dev/stdout' {} \;
find . -name "command.cpp" -type f -exec sed -i 's/<celestia\/celestiacore.h>/\"celestiacore.h\"/g w /dev/stdout' {} \;
find . -name "command.cpp" -type f -exec sed -i 's/<celestia\/imagecapture.h>/\"imagecapture.h\"/g w /dev/stdout' {} \;
find . -name "command.cpp" -type f -exec sed -i 's/<celestia\/celx_internal.h>/\"celx_internal.h\"/g w /dev/stdout' {} \;
find . -name "execution.h" -type f -exec sed -i 's/<celengine\/command.h>/\"command.h\"/g w /dev/stdout' {} \;
find ./celestia -maxdepth 1 -type f -exec sed -i 's/<celengine\/cmdparser.h>/\"cmdparser.h\"/g w /dev/stdout' {} \;
find ./celestia -maxdepth 1 -type f -exec sed -i 's/<celengine\/command.h>/\"command.h\"/g w /dev/stdout' {} \;
find ./celestia -maxdepth 1 -type f -exec sed -i 's/<celengine\/execution.h>/\"execution.h\"/g w /dev/stdout' {} \;
find . -type f -exec sed -i 's/<celengine\/cmdparser.h>/<celestia\/cmdparser.h>/g w /dev/stdout' {} \;
`

**Comment by pirogronian** [comment]
It looks like you forked really old code branch. Please fork master.

**Comment by 375gnu** [comment]
A lot of files have line-endings changed, so they are included to the PR (I have no idea what 's wrong with images)

**Comment by dlshcbmuipmam** [comment]
> It looks like you forked really old code branch. Please fork master.

@pirogronian This is not the problem :)

**Comment by dlshcbmuipmam** [comment]
> A lot of files have line-endings changed, so they are included to the PR (I have no idea what 's wrong with images)

@375gnu Yeah, sounds like this is the problem. 

Git should handle this stuff automatically, I don't know how those file were added into git, but it seems like they were not converted automatically. For example, when I do `vi -b src/tools/xindex/readme.txt" in my linux machine, there are CRLF which shouldn't exist. Git now detect those stuff after I move the files.

I guess the same thing happens to the image as well, consider it is 1 byte change, it should be something related to the end-of-file.

**Comment by dlshcbmuipmam** [comment]
> all that stuff is handled by https://github.com/OpenSpace/Spice/blob/master/CMakeLists.txt

@375gnu I know, but it seems like they are not handled properly. I can't compile my code without the addition include in the CMakeLists.txt. 

'''
Celestia/src/celephem/spiceinterface.cpp:12:
Celestia/thirdparty/Spice/include/SpiceUsr.h:175:13: fatal error: SpiceZpl.h: No such file or directory
    #include "SpiceZpl.h"
compilation terminated.
src/celephem/CMakeFiles/celephem.dir/build.make:335: recipe for target 'src/celephem/CMakeFiles/celephem.dir/spiceinterface.cpp.o' failed
'''
             ^~~~~~~~~~~~

**Comment by dlshcbmuipmam** [comment]
@375gnu Aha, now I know how to do it properly, I should do a `get_target_property(SPICE_INCLUDE_DIR Spice INCLUDE_DIRECTORIES)` in the root CMakeFiles.txt

See my modification to the latest commit.

**Comment by dlshcbmuipmam** [comment]
@375gnu @pirogronian Now I am satisfied with the changes, any other comments?

**Comment by pirogronian** [comment]
Please check what causes this massive files update. I'm afraid it can mess the repo. Maybe it's something in your IDE setting or with your system' clock.

**Comment by dlshcbmuipmam** [comment]
@pirogronian This should be related to the auto crlf https://help.github.com/en/articles/configuring-git-to-handle-line-endings. 

Well, I just set it to auto, and I found that there are inconsistency in the master branch, for example src/tools/xindex/readme.txt is CRLF in my linux machine, while src/celestia/qt/qtappwin.cpp is LF. 

It turns out that git suddenly detect some unconverted CRLF after I move the other files, possibly because it rescans the directory.

It shouldn't cause any trouble, unless some of the codes depends on the byte code explicitly.

At least, it runs normally in both my Windows and Linux machines.

**Comment by 375gnu** [comment]
> Well, I just set it to auto, and I found that there are inconsistency in the master branch, for example src/tools/xindex/readme.txt is CRLF in my linux machine, while src/celestia/qt/qtappwin.cpp is LF.

Yes, unfortunately there are a lot files with EOL mess, but for now let's keep it as is.

**Comment by dlshcbmuipmam** [comment]
>     2. what's wrong with the original ico?

After git rescan the ico and changes its EOL, the compiler (or the resource manager, whatever) complain something about the bit. I will see if I can prevent this change by ignoring those EOL changes.

**Comment by dlshcbmuipmam** [comment]
@375gnu Done

**Pull request merged**
