### PR TITLE
Upgrade project to VS 2017, and update for 64-bit support.

### PR DESCRIPTION
**Pull request by dbrant**
This set of commits allows us to build the project using Visual Studio 2017, as well as updates the code for 64-bit Windows (and adds an x64 build target). Other notes:

- Upgrade to Eigen version 3.3, and update the code accordingly.
- Upgrade to libpng 1.6.29.

### CODE REVIEW

**Comment by dbrant** [comment]
This would take care of #1 as well.

**Comment by CelestiaProject** [comment]
Hey. Thanks for the work you've done. It is really big and important for us. Your Celestia version compiles for Win32 and Win64 correctly? Celestia works without errors?

**Comment by CelestiaProject** [comment]
Also interested in QT version, since it will be the basis for Celestia 1.7.0

**Comment by Alexell** [comment]
FMOD was taken from [here](http://www.fmod.org/download) (**FMOD Studio for Unreal Engine 4 (4.15)** section. I think that I did not use it correctly, because Celestia sometimes crashes with fmod.dll exception. (described in #6)

If you can help to properly use FMOD, that it works correctly on x86 and x64, and also supported on Mac and Linux (Celestia is cross-platform) - I will be very grateful to you.

**Comment by dbrant** [comment]
To answer your questions:
- Yes, with these patches, Celestia compiles successfully for Win32 and 64, and runs without errors. The only issue seems to be with FMOD, as you've described.
- I haven't tried building it with Qt, but I can't imagine that these patches break the existing Qt frontend, since none of my changes really touch the Qt side of things. I'll give it a try later.  I'll also verify that it still builds and runs correctly in Linux and Mac.

I did also have a question of my own:
- How do you generate the installer package (for Windows)? I'm not too familiar with making installers; I've used NSIS a long time ago, but it doesn't seem like that's being used here...

**Comment by Alexell** [comment]
> Yes, with these patches, Celestia compiles successfully for Win32 and 64, and runs without errors. The only issue seems to be with FMOD, as you've described.
If you can properly connect FMOD, so that it works on win32, win64, qt, mac and linux - we will be very grateful, like many users who will then use the program.

> ... none of my changes really touch the Qt side of things ...
If we update the project, I would like to ask you to update the QT version. Now I use QT4 (I compile with QT 4.8.0 and QT Creator 2.5.2). I would like to use the new QT and QT Creator, respectively.

> How do you generate the installer package (for Windows)?
Previously Celestia installer was collected through Inno Setup (file celestia.iss). Now before the release we are still far away, so I did not think what program we will use for this.

**Pull request merged**
