### PR TITLE
Feature/linerender/v4

### PR DESCRIPTION
**Pull request by 375gnu**

### CODE REVIEW

**Comment by 375gnu** [comment]
@levinli303 could you check here if you observe that issue with darkened orbits with this branch?

**Comment by TheLostProbe** [comment]
i tested on desktop and the bug appears to be present, but it sort of flickers in a really weird way, and it only occurs at certain distances. also some depth sorting bugs with the orbits are present. i guess we will wait and see if this is apparent on mobile as well
https://user-images.githubusercontent.com/67564416/197439341-59aee95d-fa23-48d7-b62a-9cdf80135ffa.mp4

**Comment by 375gnu** [comment]
@TheLostProbe @levinli303 could you also check the same with `master` branch?

**Comment by TheLostProbe** [comment]
I'm in bed on my phone so Lev will have to check

**Comment by levinli303** [comment]
master branch does not have the issue.

**Comment by levinli303** [comment]
Seems to have been fixed with the latest commit to this branch.

**Comment by levinli303** [comment]
assertion has been hit starting up with ANGLE (drawing line as triangles)

Screen Shot 2022-10-26 at 18 59 01

**Comment by 375gnu** [comment]
@levinli303 i've removed assertions as they always fail because the vectors are freed.

**Comment by TheLostProbe** [comment]
a thought came to my mind regarding the optimization of this line renderer, since the current one lags when there are too many orbits/labels on the screen. of course, this is to be expected, but it should at least not lag that badly when trying to view for example jupiter's minor moon system, which it does when using the current line renderer

**Comment by 375gnu** [comment]
@TheLostProbe for better precision we should use 64bit floats (doubles) instead of 32bit floats supported by GPUs. So all computation are done on CPU. Taking into account that most of the current CPUs are multicore we can try to parallelize computations and maybe even offload some computations to GPU, but this is not related to this change.

**Comment by 375gnu** [comment]
@levinli303 anything else to fix?

**Comment by levinli303** [comment]
I'll verify on ANGLE later.

**Comment by levinli303** [comment]
symbols are missing for reference vectors, XYZ, etc

Screenshot 2022-11-08 at 20 26 50

**Comment by 375gnu** [comment]
@levinli303 letters should be back now

**Pull request merged**
