### PR TITLE
Bg translation and corrections

### PR DESCRIPTION
**Pull request by RacerBG**
And this is the complete translation for Celestia 1.7. :)

EDIT: Looks like I messed up, I don't know why this conflicts happened... And I don't know how to fix them. :(

### CODE REVIEW

**Comment by 375gnu** [comment]
you have used old master, before i added your translations from transifex

**Comment by RacerBG** [comment]
@375gnu Thank you very much! Should I close this PR and then delete my fork to prevent further conflicts?

**Comment by 375gnu** [comment]
you can keep your fork updated. in that case you will not have any merge conflicts.

**Comment by RacerBG** [comment]
I will close this PR then and clean the mess at my fork first.

**Pull request closed without merging**
