### PR TITLE
Various fixes to win32 front end

### LINKED ISSUE #622: Garbled list box in Chinese environment
Garbled list box in Chinese environment.
OS: Windows
Version:1.6.2 beta2

### PR DESCRIPTION
**Pull request by eyvallah**
I'm not sure if we should add WC_NATIVEFONTCTL to every dialog though, but I found that in dialogs without WC_NATIVEFONTCTL, the Chinese text in popup buttons were a bit oversize to fit in the menu. Adding WC_NATIVEFONTCTL make the size look correct too.

Closes #622

### CODE REVIEW

**Comment by eyvallah** [comment]
BTW how do we generate the localized .dll now?

**Comment by 375gnu** [comment]
Let's check how this looks with other locales and let me read about WC_NATIVEFONTCTL.

Regarding your question - this file is used https://github.com/CelestiaProject/Celestia/blob/1.6.x/po/translate_resources.pl. Please note the branch. It accepts either win32 or x64 to select a platform.

**Comment by eyvallah** [comment]
without WC_NATIVEFONTCTL

Screen Shot 2020-06-21 at 8 08 05 PM

some text were clipped in the popup button menu

with WC_NATIVEFONTCTL

Screen Shot 2020-06-21 at 8 03 12 PM

text were smaller

**Comment by 375gnu** [comment]
Hi @eyvallah , could you backport this PR for 1.6.2 as well?

**Comment by eyvallah** [comment]
> could you backport this PR for 1.6.2 as well?

sure but how do we build 1.6.2 win32?

**Comment by 375gnu** [comment]
i have a virtual machine with windows

**Pull request merged**
