### PR TITLE
Remove thirdparty submodules

### PR DESCRIPTION
**Pull request by levinli303**
just use the system ones.

### CODE REVIEW

**Comment by levinli303** [comment]
uh, it seems cspice is not offered in apt as a package.

**Comment by munix9** [comment]
fmt also seems to be mandatory
By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has ...

**Comment by levinli303** [comment]
> fmt also seems to be mandatory
> By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has ...

fixed now, install libfmt-dev on Ubuntu

**Comment by 375gnu** [comment]
this is too early. let's keep them for 6-12 month

**Comment by 375gnu** [comment]
let's go!

**Review by 375gnu — APPROVED** [review]

**Pull request merged**
