### PR TITLE
Add DejaVu fonts and use them by default

### PR DESCRIPTION
**Pull request by 375gnu**

### CODE REVIEW

**Comment by SevenSpheres** [comment]
You might want to adjust the font size a bit; it looks bigger than the old font.
oldfont
dejavufont

**Comment by munix9** [comment]
```
--- a/fonts/CMakeLists.txt
+++ b/fonts/CMakeLists.txt
@@ -1,3 +1,3 @@
-file(GLOB FONTS_SOURCES *.txf)
+file(GLOB FONTS_SOURCES "*.txf" "*.ttf")
 
 install(FILES ${FONTS_SOURCES} DESTINATION "${DATADIR}/fonts")
```

**Comment by 375gnu** [comment]
Thank you @munix9!

**Comment by 375gnu** [comment]
> You might want to adjust the font size a bit; it looks bigger than the old font.

If you don't like, you can adjust it in your `$HOME/.celestia.cfg`, provided sizes assume 96 dpi screen

**Comment by munix9** [comment]
I think debian configs still needs adjustments like
- libfreetype6-dev
- -DENABLE_TTF=ON

as defined in the .travis.yml

**Comment by 375gnu** [comment]
yeah, dunno why i decided that packaged builds don't require it

**Pull request merged**
