### PR TITLE
Add openclusters.dsc

### PR DESCRIPTION
**Pull request by SevenSpheres**
Credit to Selden Ball. Previously #551, which apparently I can't reopen after force-pushing the branch...

@LukeCEL as for adding your other files I've made branches [here](https://github.com/SevenSpheres/Celestia/tree/update-stardb) and [here](https://github.com/SevenSpheres/Celestia/tree/jsdc) as examples.

### CODE REVIEW

**Comment by 375gnu** [comment]
@SevenSpheres What about licence for this file?

**Comment by SevenSpheres** [comment]
> This Addon may be freely redistributed for educational purposes so long as all of the provided files are included.
> This Addon may not be used for any commercial benefit without explicit written permission from the author.
...that actually may not be compatible. But it's just a catalog of open clusters, with the data coming from the referenced paper.
If this catalog can't be used...well, I'll have to switch back to Andrew Tribick's one.

**Comment by 375gnu** [comment]
@SevenSpheres could you try to reach Selden and ask his permission to change the licence for this file to CC-SA-4.0 or GPL2.0+ or something else considered free?

**Comment by 375gnu** [comment]
Hi @SevenSpheres , unfortunately Selden refused to change the license, so I'm rejecting this PR, sorry.

**Pull request closed without merging**
