### PR TITLE
Fix alignment of TextureFontPrivate

### PR DESCRIPTION
**Pull request by 375gnu**
should fix SIGBUS / BUS_ADRALN on Android

### CODE REVIEW

**Comment by eyvallah** [comment]
looks like this is the issue

image

**Comment by eyvallah** [comment]
https://appcenter.ms/orgs/CelestiaProject/apps/Celestia-1/crashes/errors/960553627u/overview

is this related, also SIGBUS / BUS_ADRALN @375gnu

**Comment by 375gnu** [comment]
I don't think so, all *Frame types have `EIGEN_MAKE_ALIGNED_OPERATOR_NEW`

**Comment by eyvallah** [comment]
video of Play Console producing this crash.

[crash.mp4.zip](https://github.com/CelestiaProject/Celestia/files/4818732/crash.mp4.zip)

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'motorola/harpia/harpia:6.0.1/MPIS24.241-2.50-16/16:user/release-keys'
Revision: 'p1b0'
ABI: 'arm'
pid: 15360, tid: 16438, name: GLThread 1377  >>> space.celestia.mobilecelestia <<<
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xb87ab458
    r0 b87ab458  r1 60967b56  r2 00000006  r3 60967b56
    r4 9fe3e240  r5 b87ab438  r6 999700a9  r7 9fe3e208
    r8 9fe3e1c0  r9 b6d69e40  sl 4142c2c7  fp b6d69e40
    ip 99d66ad0  sp 9fe3e1c0  lr 998fea13  pc 9996fdee  cpsr 200e0030
backtrace:
    #00 pc 002d7dee  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZNK12CachingFrame14getOrientationEd+125)
    #01 pc 002d721f  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZNK14ReferenceFrame20convertFromUniversalERK14UniversalCoordd+78)
    #02 pc 002e7ef3  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZNK13ObserverFrame20convertFromUniversalERK14UniversalCoordd+14)
    #03 pc 002e9a03  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZN8Observer23convertFrameCoordinatesERKNSt6__ndk110shared_ptrIK13ObserverFrameEE+58)
    #04 pc 002e9bdf  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZN8Observer8setFrameEN13ObserverFrame16CoordinateSystemERK9SelectionS4_+58)
    #05 pc 002e8f2f  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZN8Observer8setFrameEN13ObserverFrame16CoordinateSystemERK9Selection+22)
    #06 pc 0025370d  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZN12CelestiaCore11charEnteredEPKci+3316)
    #07 pc 00252a03  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZN12CelestiaCore11charEnteredEci+34)
    #08 pc 00d73413  /data/app/space.celestia.mobilecelestia-1/oat/arm/base.odex (offset 0xa35000)
```

**Comment by eyvallah** [comment]
> video of Play Console producing this crash.
> 
> [crash.mp4.zip](https://github.com/CelestiaProject/Celestia/files/4818732/crash.mp4.zip)
> 
> ```
> *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> Build fingerprint: 'motorola/harpia/harpia:6.0.1/MPIS24.241-2.50-16/16:user/release-keys'
> Revision: 'p1b0'
> ABI: 'arm'
> pid: 15360, tid: 16438, name: GLThread 1377  >>> space.celestia.mobilecelestia <<<
> signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xb87ab458
>     r0 b87ab458  r1 60967b56  r2 00000006  r3 60967b56
>     r4 9fe3e240  r5 b87ab438  r6 999700a9  r7 9fe3e208
>     r8 9fe3e1c0  r9 b6d69e40  sl 4142c2c7  fp b6d69e40
>     ip 99d66ad0  sp 9fe3e1c0  lr 998fea13  pc 9996fdee  cpsr 200e0030
> backtrace:
>     #00 pc 002d7dee  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZNK12CachingFrame14getOrientationEd+125)
>     #01 pc 002d721f  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZNK14ReferenceFrame20convertFromUniversalERK14UniversalCoordd+78)
>     #02 pc 002e7ef3  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZNK13ObserverFrame20convertFromUniversalERK14UniversalCoordd+14)
>     #03 pc 002e9a03  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZN8Observer23convertFrameCoordinatesERKNSt6__ndk110shared_ptrIK13ObserverFrameEE+58)
>     #04 pc 002e9bdf  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZN8Observer8setFrameEN13ObserverFrame16CoordinateSystemERK9SelectionS4_+58)
>     #05 pc 002e8f2f  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZN8Observer8setFrameEN13ObserverFrame16CoordinateSystemERK9Selection+22)
>     #06 pc 0025370d  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZN12CelestiaCore11charEnteredEPKci+3316)
>     #07 pc 00252a03  /data/app/space.celestia.mobilecelestia-1/lib/arm/libcelestia.so (_ZN12CelestiaCore11charEnteredEci+34)
>     #08 pc 00d73413  /data/app/space.celestia.mobilecelestia-1/oat/arm/base.odex (offset 0xa35000)
> ```

just found out that is is always the "chase" function that is causing it.

**Comment by levinli303** [comment]
@375gnu  I think I might have found the cause of it, we use `make_shared` to create pointers

```
        return make_shared<TwoVectorFrame>(_refObject,
                                  FrameVector::createRelativeVelocityVector(_refObject, _refObject.parent()), 1,
                                  FrameVector::createRelativePositionVector(_refObject, _refObject.parent()), 2);
```

but `EIGEN_MAKE_ALIGNED_OPERATOR_NEW` it only overrides `new` operator which is not called in `make_shared`

**Pull request merged**
