### PR TITLE
Feature/linerender/v2

### PR DESCRIPTION
**Pull request by 375gnu**

### CODE REVIEW

**Comment by 375gnu** [comment]
@levinli303 please build a beta version for mobile devices. I forced line triangulation and it looks good, but I would like to have response from users with real h/w.

**Comment by 375gnu** [comment]
@levinli303 regarding your changes made to `celmodel/*`. I don't see any support for lines wider than 1px in `cmod` files, so your changes currently are dead code. Should we revert them?

**Comment by 375gnu** [comment]
On the other hand we may want wider lines on high dpi screens.

**Comment by levinli303** [comment]
yeah it looks like indeed there is no call to glLineWidth in model, we can revert them.

**Comment by levinli303** [comment]
@375gnu  there is conflict with master branch, after fixing it, I'll build wip builds for iOS/Android

**Comment by 375gnu** [comment]
closing in favor of #1425. @levinli303 please build from it instead

**Pull request closed without merging**
