### PR TITLE
[qt] Pass '[' and ']' keys to search console

### PR DESCRIPTION
**Pull request by 375gnu**
Closes: #526

### CODE REVIEW

**Comment by 375gnu** [comment]
@SevenSpheres please test

**Comment by SevenSpheres** [comment]
Fixes brackets at least, though there may or may not be other keys that don't work.

**Comment by 375gnu** [comment]
I don't see any other keys without modifiers used by Qt GUI

**Comment by LukeCEL** [comment]
This fixes brackets. I haven't found any other keys that fail.

**Pull request merged**
