### PR TITLE
Release version 1.6.3

### PR DESCRIPTION
**Pull request by 375gnu**
@ajtribick could you build a windows release?

### CODE REVIEW

**Comment by levinli303** [comment]
let me see if there are changes needed for supporting apple silicon.

**Comment by levinli303** [comment]
this change https://github.com/CelestiaProject/Celestia/commit/6b8a1fe6b32bcb161eb801070ca9e4f5dcee7e3a should also be cherry-picked. as i observe the same flickering on apple silicon.

**Comment by levinli303** [comment]
no change to the project file is needed to support apple silicon, so we can add that to release notes as well. i will create a universal binary locally when we release.

**Comment by ajtribick** [comment]
Managed to get Windows installer built in #1663

**Comment by 375gnu** [comment]
@levinli303 could you create a mac binary and upload it to https://github.com/CelestiaProject/Celestia/releases ?

**Comment by levinli303** [comment]
Universal Mac binary is uploaded with support for x86_64 and arm64

**Pull request closed without merging**
