### PR TITLE
Add Android/iOS/Mac string for i18n

### PR DESCRIPTION
**Pull request by eyvallah**

### CODE REVIEW

**Comment by eyvallah** [comment]
Do I also need to update other .po files? @375gnu

**Comment by 375gnu** [comment]
Could we keep separately while new UIs are not added? The problem is that when we update them, all new strings will be removed because their source files are missing.

**Comment by eyvallah** [comment]
like in a separate folder po3? @375gnu

**Comment by 375gnu** [comment]
Actually I was thinking about custom branch. But a `po3` folder will be ok as well. Also please rename it to `celestia_ui.pot` that way we can have a separate file on transifex for translators flexibility.

**Comment by eyvallah** [comment]
I guess I'll do both, a separate branch (or just maybe in my fork, since the part of code are not very ready), and in a separate folder po3(but this leads me to think about existing shared items in celestia.pot...)

**Comment by pirogronian** [comment]
Sorry, in fact I reviewed only last commit. Too tired to work...

**Comment by eyvallah** [comment]
@pirogronian  it's ok, this is a draft. I should close it for now.

**Pull request closed without merging**
