### PR TITLE
Add a tick method with elapsed time parameter

### PR DESCRIPTION
**Pull request by levinli303**

### CODE REVIEW

**Comment by 375gnu** [comment]
What's the purpose of this method?

**Comment by levinli303** [comment]
platform API can give us a predicted timing for presentation, using this time instead of current time can probably reduce latency.

**Comment by 375gnu** [comment]
Could you leave an appropriate comment in celestiacore.h then?

**Comment by levinli303** [comment]
> Could you leave an appropriate comment in celestiacore.h then?

added

**Review by 375gnu — APPROVED** [review]

**Pull request merged**
