### PR TITLE
Calculate planets shading in fragment shaders

### PR DESCRIPTION
**Pull request by 375gnu**
This is not a final version, it requires cleanup from debug and unused code. It's pushed so we can test it with wider audience.

Especially I would like to hear results from old hardware owners (DX9.0 class, not even DX9.0c, and old mobiles / low power devices with GL ES 2.0).

This is a prerequisite for sRGB/gamma corrected output, see #834 for screenshots.

### CODE REVIEW

**Comment by TheLostProbe** [comment]
> Especially I would like to hear results from old hardware owners (DX9.0 class, not even DX9.0c, and old mobiles / low power devices with GL ES 2.0).

i will see if i can test this on some of my old computers and phones

**Comment by SevenSpheres** [comment]
[HD 1690 by Karistus](https://github.com/CelestiaProject/Celestia/files/11826692/hd_1690.zip) - the planet is invisible on this branch

**Comment by 375gnu** [comment]
@SevenSpheres please test now https://github.com/CelestiaProject/Celestia/actions/runs/5354420554

**Comment by SevenSpheres** [comment]
HD 1690 b is working on that build

**Review by ajtribick — APPROVED** [review]

**Comment by levinli303** [comment]
Created an APK here for testing: https://dev.azure.com/CelestiaProject/Celestia/_build/results?buildId=2456&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by 375gnu** [comment]
Let's go!

**Comment by levinli303** [comment]
I also updated https://celestia.mobi/web with the latest code

**Pull request merged**
