### PR TITLE
Fix blending state when drawing stars and objects as points

### PR DESCRIPTION
**Pull request by 375gnu**
Closes: #1409

### CODE REVIEW

**Comment by 375gnu** [comment]
@TheLostProbe please confirm that this patch fixes the issue.

**Comment by TheLostProbe** [comment]
its gone. good riddance black square bug!
image
image
image

**Review by levinli303 — APPROVED** [review]

**Comment by levinli303** [comment]
@375gnu it seems we should still keep the one in `renderObjectAsPoint` to fix https://github.com/levinli303/AndroidCelestia/issues/47

**Comment by 375gnu** [comment]
@levinli303 please see my comment in #1454

**Pull request merged**
