### PR TITLE
Set line width according to DPI

### PR DESCRIPTION
**Pull request by levinli303**

### CODE REVIEW

**Comment by levinli303** [comment]
what's up with travis? it's not even running

**Review by 375gnu — APPROVED** [review]

**Comment by 375gnu** [comment]
i'll check travis later, i don't see any celetia repos in its settings

**Comment by 375gnu** [comment]
Here is the reason:
> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

**Comment by 375gnu** [comment]
i think we should try github actions

**Comment by levinli303** [comment]
> i think we should try github actions

yeah, it should be possible. im trying to set up on Azure for the mobile ones.

**Comment by levinli303** [comment]
@375gnu can we disable travis for now, and merge the two PRs? I can set up with azure later, I have sent a request for azure to access the repo earlier and it is still pending.

**Comment by 375gnu** [comment]
@levinli303 i've disabled. you can merge this.

**Pull request merged**
