### PR TITLE
Enable visual styles for Win32 controls

### PR DESCRIPTION
**Pull request by levinli303**
https://docs.microsoft.com/en-us/windows/win32/controls/cookbook-overview

### CODE REVIEW

**Comment by levinli303** [comment]
looks like it works.

new vs old

Screen Shot 2022-01-09 at 9 22 18 PM

**Comment by SevenSpheres** [comment]
Huh, oddly enough 1.7.0-win does look like the "old" image on my end (as did 1.6.1), even though 1.6.2 looks like the "new" image.

**Comment by levinli303** [comment]
@SevenSpheres did you use the one from the artifacts generated by this PR? I just copied the celestia-win.exe from the artifacts to the win1.7.0 installation and it works.

**Comment by SevenSpheres** [comment]
No, I was referring to previous builds. I just saw the "new" image and thought "doesn't it already look like that?" because it does on 1.6.2.

**Comment by levinli303** [comment]
> No, I was referring to previous builds. I just saw the "new" image and thought "doesn't it already look like that?" because it does on 1.6.2.

yes. We used to use this manifest file which would enable visual styles in 1.6.x. but when we switched to cmake, we stopped using the file and cmake defaults to generating a manifest that does not support visual styles.

**Review by 375gnu — APPROVED** [review]

**Pull request merged**
